client_id = "7ce4ab9fe3899967c5350389c354edab"
name = "mapapp"
handle = "mapapp-1"
application_url = "https://mapapp-dun.vercel.app/auth"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[access_scopes]
scopes = "write_products"

[auth]
redirect_urls = [ "https://mapapp-dun.vercel.app/auth/callback" ]

[webhooks]
api_version = "2025-07"