# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3a4811568d3fedf243ee35d222f2ed7c"
name = "mapmaker2"
application_url = "https://inter-pale-wal-watch.trycloudflare.com"
embedded = true
handle = "mapmaker2"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://inter-pale-wal-watch.trycloudflare.com/auth/callback", "https://inter-pale-wal-watch.trycloudflare.com/auth/shopify/callback", "https://inter-pale-wal-watch.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
