# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fc38a6597a3c44320deb9ea096751aed"
name = "mapapp"
application_url = "https://ec-tomato-hollow-ppm.trycloudflare.com"
embedded = true
handle = "mapapp-2"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://ec-tomato-hollow-ppm.trycloudflare.com/auth/callback", "https://ec-tomato-hollow-ppm.trycloudflare.com/auth/shopify/callback", "https://ec-tomato-hollow-ppm.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
