name = "Product Map Builder"
type = "theme"

[blocks]
  [blocks.map_builder]
  name = "Map Builder"
  target = "section"
  
[[assets]]
name = "map-builder-styles.css"

[[assets]]
name = "map-builder-loader.js"